#!/bin/bash

#
#
#  Author Yuriy Us. 3/16/16.     Ver 1.0

function Usage ()
{
cat << EOF
-----------------------------------------------------------------------------
Script to package whole directory in <file_name>.tgz file>

	Usage: Pack! <Src_Dir> <FileName>
	Where 
		<Src_Dir> - Source directory
		<FileName> - Nane of Package
	Note. Extention tgz will be added to your file name automaticaly
-----------------------------------------------------------------------------
EOF
}

if [ -d "$1" ] ; then
       tar -zcvf $2.tgz $1
else
	Echo Error: Directory $1 does not exist      
	Usage
	exit 1
fi
